### ISSUE TITLE
Review: Set up your Kanban board.

### ISSUE THREAD

**Issue by Zafron047** [Zafron047/space_travelers_hub#25]
Dear Reviewer,

Please check [this Kanban Board](https://github.com/Zafron047/space_travelers_hub/projects/1) consisting 2 team members.

- [x] Created an empty repository for group project.
- [x] Opened GitHub project (Kanban board) in our team repo.
- [x] Removed all cards with Team3 in the title.
- [x] All cards on our Kanban board now have assignees.

We appreciate your kind effort.

Regards,

@Zafron047 @zuhebahmed88091

**Comment by TedLivist** [comment]
## STATUS: APPROVED ✔️ ✔️

Hi @Zafron047 and @zuhebahmed88091,

✔️ Tasks are complete and well assigned

Your project is complete!  There is nothing else to say other than... it's time to go ahead with the project :shipit: 
Congratulations! 🎉

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the Issue thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
